### ISSUE TITLE
Is there a plan to take the bottom section and also make them posts?

### ISSUE THREAD

**Issue by tknx** [andrewbanchich/spectral-jekyll-theme#3]
I noticed your Gitlab is empty too, so not sure if this is a dead theme or not,

But if not, are there plans to make the bottom purple section also pull from a set of posts?

**Comment by andrewbanchich** [comment]
Hi, yeah the README is out of date. I'll remove the part about GitLab.

The theme still should work, but I have not had the opportunity to maintain a lot of them in some time (including this). So as of now, I don't have plans to add more features to this one.
